### ISSUE TITLE
Fix testing failure on master branch

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-informix#21]
master branch is failing due to error:
```
1)  "before all" hook:
   TypeError: Cannot set property deleteAll of #<SQLConnector> which has only a getter
    at Object.<anonymous> (lib/informix.js:275:62)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (index.js:8:18)
    at require (internal/module.js:12:17)
    at global.getDataSource.global.getSchema (test/init.js:28:27)
    at Context.<anonymous> (test/informix.discover.test.js:17:15)
```

**Comment by jannyHou** [comment]
closing it in favour of https://github.com/strongloop-internal/scrum-loopback/issues/1259

**Comment by eddiemonge** [comment]
This is not a CI issue. It occurs locally as well.

**Comment by kjdelisle** [comment]
We have a task to track the work of the informix rewrite and testing. Closing as duplicate
